#!/usr/bin/env sh

WIDTH=${WIDTH:-2}
HEIGHT=${HEIGHT:-200}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

	# the position of the upper left corner of the popup
	posX=$(($BLOCK_X - $WIDTH / 2))
	posY=$(($BLOCK_Y - $HEIGHT))

	#i3-msg -q "exec yad --calendar --undecorated \
	#	--mouse --width=350 --height=250 \
    #    --escape-ok --selectable-labels --selectable-labels \
    #    --buttons-layout=spread --timeout=120 --timeout-indicator=top \
    #    > /dev/null"

	# i3-msg -q "exec yad --calendar --undecorated \
	# 	--posx=1600 --posy=30 --width=315 -- \
	# 	--height=200 --escape-ok > /dev/null"

	i3-msg -q "exec gnome-calendar"
esac
echo "$LABEL$(date "$DATEFMT")"
echo "$LABEL$(date "$SHORTFMT")"
