#!/usr/bin/env bash
#----------------------------------------------------------------------------#
#           _  _____          _                 _                            #
#          | ||___ /   ___   | | __ _ __  _ __ (_) ____ ___                  #
#          | |  |_ \  / _ \  | |/ /| '__|| '__|| ||_  // _ \                 #
#          | | ___) || (_) | |   < | |   | |   | | / /| (_) |                #
#          |_||____/  \___/  |_|\_\|_|   |_|   |_|/___|\___/                 #
#                                                                            #
#----------------------------------------------------------------------------#
#  by: Leonel Carrizo (2024).                                                #
#      This script help to update the current keyborad layout.               #
#      If it activate by click it call the script to change the layout       #
#      If is activate by a signal comming from changer layout script,        #
#      It will just show the current layout.                                                                      #
#----------------------------------------------------------------------------#

layout=$(setxkbmap -query | grep layout | cut -d ' ' -f 6)
layout=${layout^^}

if [ "$BLOCK_BUTTON" = "1" ]; then
  exec /home/l3o/.local/bin/kb-layout

elif [ -z "$BLOCK_BUTTON" ]; then
  echo " $layout"
fi
